Helper/Profile.php, Model/ResourceModel/Profile.php, Setup/Patch/Schema/CreateSolvedataProfileTable.php
This PR:
- Changes the profile ID lookup logic to disregard the website ID so it can find the profile ID for the given email even if it was used in another website
- Does not save the profile ID if it already exists for another website -- this change prevent's the `solvedata_profile` table's unique constraint from being violated
**Considerations:**
The `solvedata_profile` table has a compound unique constraint on `(email, store_id)`. It appears like mysql will automatically create an index for these columns based on this unique constraint. ~Unfortunately the updated profile query has been changed to no longer supply the website ID, which will likely mean that mysql cannot take advantage of this index since we only referencing a subset of its columns.~ (see comment)
The solution to avoid a …
=> Support users using the same email address across multiple Magento websites

Model/Event.php, Model/ResourceModel/Event.php
This moves to sending a batch of events one at a time, along with providing more information in the event of an exception.
Note: This change will significantly slow down queue processing if there are many exception-causing events, as the batch processing will not proceed past an event that throws an exception.
**Testing**:
=> Process one event at a time to limit failure mode

Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/RegisterGuestCustomer.php, Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
This PR:
- Adds extra error handling when mapping event payloads to reduce the chances that we fail to process an event (and hence the entire batch) if we encounter any data issues. This error handling causes the events to omit some non-essential fields if there is an unexpected error while processing.
- Adds profile attributes when a profile is created/updated via the guest checkout profile mutation.
- Changes the store & website attributes on a profile to be able to handle the situation where the same profile uses multiple Magento stores. The current behaviour is that the last store used clobbers any previous store's attribute. While this change isn't super relevant to the rest of the PR, it seemed best to include it here to avoid merge conflicts.
=> Add extra error handling to be defensive when mapping event payloads

Helper/Profile.php, Model/Event/Transport/Adapter/GraphQL.php, Model/Event/Transport/Adapter/GraphQL/Mutation/CheckoutCartSaveAfter.php, Model/Event/Transport/Adapter/GraphQL/Mutation/CustomerAccountEdited.php, Model/Event/Transport/Adapter/GraphQL/Mutation/CustomerAddressSaveAfter.php, Model/Event/Transport/Adapter/GraphQL/Mutation/CustomerLogin.php, Model/Event/Transport/Adapter/GraphQL/Mutation/CustomerLogout.php, Model/Event/Transport/Adapter/GraphQL/Mutation/CustomerRegisterSuccess.php, Model/Event/Transport/Adapter/GraphQL/Mutation/NewsletterSubscriberSaveCommitAfter.php, Model/Event/Transport/Adapter/GraphQL/Mutation/OrderCancelAfter.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/ConvertCart.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/CreateOrUpdateOrder.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/RegisterGuestCustomer.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderShipmentSaveAfter.php, Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, Model/Profile.php, Model/ResourceModel/Profile.php, README.md, Setup/Patch/Schema/CreateSolvedataProfileTable.php
This PR is based off @natashasheviakova's PR in the previous repository.
It replaces all usages of `sid` with the respective `id` or `profile_id` (depending on the mutation). This means that the plugin will be compatible with Solve's API when/if backwards support for `sid` is dropped.
This PR refactors the code to reference Profile IDs rather than SIDs, but it stops short of renaming the `sid` columns in the database schema. Even though we should be able to do this in a Magento migration (which should automatically be applied when the extension is upgraded via the `magento setup:upgrade` command) we have decided that it's better not to require additional migrations unless completely necessary to reduce the possibility for things to go wrong when external parties are maintaining this …
=> Migrate sid usages to profile ID in GraphQL usage

Model/Adminhtml/Source/Event/Store.php, Model/Event/DataProvider.php
By default Magento skips over the "default store" (i.e. the store with the zeroth ID, [see here](https://github.com/magento/magento2/blob/2.3.5/app/code/Magento/Store/Model/StoreManager.php#L179)). This breaks the admin UI from displaying any details on events originating from the default store.
=> Fix events from the default store breaking the Admin Events UI

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, Model/ResourceModel/Event.php
This fix is to explicitly map orders with status `paymentexpress_failed` through as canceled orders in Solve.
This is because the paymentexpress extension appears to dispatch a `sales_orders_save_after` event that (incorrectly) shows the order as pending. I say incorrectly because if we re-import the order, the event's payload has the order in state canceled instead of  shows up with state `canceled` despite  This is odd because the order appears to be canceled when fetched directly from the database (shown by manually importing the order to Solve Data) despite when there is are no additional `sales_orders_save_after` events which have occurred since.
With this fix, there is now no difference in the parameters `create_or_update_order` mutation between the `order_cancel_after` and the …
=> Add work around to prevent failed paymentexpress payments from uncancelling orders

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
PHP's `array_merge` function reindex array's indices which is a problem when the array is actually an associative array containing numeric attribute IDs rather than being a sparse array.
This can cause orders's `create_or_update` mutation requests to be invalid when the order contains products with numeric attributes.
=> Fix item attribute merging with numeric attribute keys

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
Adding these additional fields allows us to identity orders containing items on sale. This is in addition to the the information contained in the adjustments array for which tells us about discounts for the entire cart -- i.e. discount vouchers being applied at checkout.
=> Send through Magento's price, final price & original price fields as item attributes

Model/Config.php, Model/Event.php, Model/ResourceModel/Event.php, etc/adminhtml/system.xml, etc/config.xml
This PR makes batch sizing configurable so we can tweak the performance (if necessary) of the import cron when processing large amounts of events (i.e. during a full historic import).
=> Add config settings for the batch sizing

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
The adjustment value comes from Magento’s `gift_cards_amount` field, however it should be noted that this information is duplicated across multiple different fields:
```json
"gift_cards": "[{\"i\":1234,\"c\":\"<<REDACTED>>\",\"a\":20,\"ba\":20,\"authorized\":20}]",
"base_gift_cards_amount": "20.0000",
"gift_cards_amount": "20.0000",
"base_gift_cards_invoiced": "20.0000",
"gift_cards_invoiced": "20.0000",
```
In the end, I chose to use the value from `gift_cards_amount` for this adjustment.
I’ve simply called the adjustment Gift Card, even though it should be possible to use more than just a single one.
However just in case it’d come in useful for any queries into how people are using gift cards I’ve mapped the JSON content from `gift_cards` into the order’s attributes (taking care to …
=> Add order adjustment for gift cards

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
This PR fixes a bug introduced in #13. `STATE_PENDING` is a non-existent constant on the `Order` class and this causes nearly all order events to fail to be processed.
I'm surprised that this code was so obviously broken. I either didn't test PR #13 at all or refactored it at the last minute. While a bug this obvious would definitely show up in smoke tests prior to cutting release, I'm still not happy it slipped through in the first place.
=> Fix mistaken non-exist constant reference

Model/Event.php, Model/Event/Transport/Adapter/GraphQL.php
This PR contains a bug fix and an improvement to error handling for events.
The fix is for a bug that was introduced in #17 where the error handling code path would always fail due to an undefined variable.
The improvement is to make sure we capture any exceptions that occur from side the GraphQL mapping logic and add them into the event entity's informational `request` JSON blob.
=> Fix error handling for event batches

composer.json
We have an existing LICENSE file in the repo however Composer requires the license to be referenced explicitly in the `composer.json` file.
This is to prevent the following warning in packagist
https://packagist.org/packages/solvedata/plugins-magento2
=> Reference existing Apache 2 license in Composer

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
This PR removes the code that manually sets the payment status to refunded in the Magento extension.
This is because the `REFUNED` payment status was removed in a breaking API change. Currently any orders that are refunded fail to be sent through to Solve. This change ignores setting the payment status on refunded orders so we don't unnecessarily create errors while proper payments support is implemented.
**TODO**
=> Remove refunded payment status from the integration

Controller/Adminhtml/Event/ResendEvent.php, view/adminhtml/ui_component/solvedata_events_event_listing.xml
This PR adds the ability to re-enqueue an event into the events table effectually resending it to Solve.
This is handy for events (i.e. logins, carts, etc) where we cannot reimport the underlying resource to trigger the event to be resent.
**Screenshots**
Resending an event:
Attempting to resend all events (currently not supported):
=> Add an action to resend events

Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/CreateOrUpdatePayment.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/CreateOrUpdateReturn.php, Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, etc/solvedata_events.xml
This PR adds support for creating payment & return resources in Solve's GraphQL API based off an order's payment details.
Is this a little crude as these payments & returns aren't actually created for individual "payments" (or transactions as Magento calls them) but rather as a single logic payment (and a return if some money is refunded) that encapsulates the total amount paid/refunded. I went down this route because I couldn't see any events that were fired when a Magento transaction is created.
I believe this is a fair trade off to make, the only down side is that we lose the granularity that Magento has in their transaction resource. But then again our payment API isn't as in-depth as Magento's anyway.
I've also removed all places where we manually set order's `paymentStatus` as these …
=> Add support for Solve's payment & return resources

Model/Config.php, Model/Event/Transport/Adapter/GraphQL.php, etc/adminhtml/system.xml, etc/config.xml
This feature introduced race conditions between GraphQL requests and therefore we recommend leaving it disabled.
This PR removes it entirely to ensure it's not enabled by accident.
=> Remove the option to send GraphQL requests in parallel

Model/ResourceModel/Event.php
This PR changes the purging historical events cron job to only delete up to 1000 events at a time.
This is to prevent the theoretical possibility of this cron job locking the table for an extended period of time when this version is first deployed to existing production environments with a large backlog of historic events to delete.
This change makes use of MySQL's non-standard support for delete queries following the form `DELETE ... ORDER BY LIMIT ...`. These queries wouldn't work with another DB like Postgres but it appears like Magento only supports MySQL so it should be safe to use this non-portable SQL feature. Alternatively we could rewrite this query to use delete where in subquery, but that seemed more complicated so I decided to stick with it as is.
=> Add a maximum batch size when purging historical events

Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/ConvertCart.php
I realised that the plugin won't attempt to convert guest customer's carts even if we are have enabled tracking anonymous carts.
This PR fixes this by attempting to convert the carts when the feature flag is enabled.
Since cart conversion is the riskiest mutation, it is the last mutation to be attempted for order creation. This means that even if we introduce a bug in this mutation class the plugin should still create the order, payment & return (if any) before failing.
=> Convert guest customer's carts when the anonymous carts feature is enabled

Model/Event/RegisterHandler/Sales/OrderCancel.php, Model/Event/RegisterHandler/Sales/OrderSave.php, Model/Event/RegisterHandler/Sales/OrderShipmentSave.php, Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, composer.json, etc/module.xml, etc/solvedata_events.xml
This PR fixes a few bugs found from releasing the previous version `1.0.64`.
Namely:
- Uses a default payment ID of `${ORDER_ID}-payment` when no other suitable ID can be found on the payment data.
- Only adds a gift card adjustment discount when there is a non-zero total from the gift card.
- Logs the order ID before failing processing an order because it's got an unset state. This does not fix the error but will allow us to track down which orders are causing these errors.
This PR also changes the ordering of the convert cart mutation to be before the payment. This is just so a failed payment mutation doesn't stop us from marking the cart as successfully converted.
=> Use a default payment ID when no other suitable ID exists & additional fixes

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
This PR applies the same fix as #35 but for returns.
=> Handle missing payment entity IDs for returns

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
Currently the Magento extension uses tax exclusive prices with an adjustment for tax while the discount adjustment factors in the discount on tax. Unfortunately this means that when a discount is applied the resulting total is less than the actual total for the order.
This PR solves this by adding a tax compensation adjustment to match sure the total price is correct.
In future we should review whether our method of handling tax is the best solution (note our Shopify integration is tax inclusive in its subtotals).
**Food for thought**
This PR changes the discount adjustment to only be included in the order's adjustment if the discount amount is non-zero. This subtlety changes the shape of data in the query engine which could break queries which expect the discount amount adjustment to …
=> Add an adjustment for discount tax compensation

composer.json, etc/module.xml
This PR bumps the plugin version to `v1.0.66` so the latest changes in main can be published into a Packagist version.
=> Bump plugin version to 1.0.66

Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/ConvertCart.php
This bug is caused because the previous versions of the code only tested whether the `customer_is_guest` flag was present.
Unfortunately while this flag is only present for new orders if the user was a guest, historically imported orders have this flag as `0`. Therefore we should actually test the value of the flag.
The plugin already does not attempt to convert carts when the order was created before the Solve plugin was first installed via testing for the presence of the `is_object_new` extension attribute. However I would expect this change to cause many historic orders to have their convert cart calls fail as their cart may not actually exist because we have only recently been tracking guest carts since a couple of versions ago.
=> Fix historic orders not converting carts

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
I've since realised that a payment's entity ID is only generated and stored in the payments data when the payment (or transaction) is stored in the DB. Because different payment extensions store their transactions at different stages of an order's lifecycle we shouldn't rely on the `entity_id` at all.
This is to avoid the same order's payment being created twice under two different Solve payment IDs.
=> Generate stable IDs for payments/returns instead of relying on payments entity ID

Model/Config.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/ConvertCart.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/RegisterCustomer.php, Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, README.md, composer.json, etc/adminhtml/system.xml, etc/config.xml, etc/module.xml, etc/solvedata_events.xml, tests/mutations/ConvertCartTest.php, tests/mutations/CreateOrUpdateOrderTest.php, tests/mutations/CreateOrUpdatePaymentTest.php, tests/mutations/CreateOrUpdateReturnTest.php, tests/mutations/RegisterCustomerTest.php
This PR changes the series of mutations made when processing order events so they always send through a `create_or_update_profile` mutation even when when the order wasn't placed by a guest customer.
This is because the profile may not exist when we are importing historic orders. Since order events are relatively rare when compared with cart events we should not mind doing the extra `create_or_update_profile` mutation for every order.
In addition this PR also:
- Adds a configuration option to attempt cart conversion for historical orders. This will allow us to convert carts for orders where their `convert_cart` mutations previously failed.
- Introduces unit tests. These will be fleshed out in future PRs.
- Fixes a bug in the return mutation due to a missing variable (uncovered by unit …
=> Ensure a profile exists in Solve before importing Magento orders & other importing fixes

Setup/Patch/Schema/DropSidUniqueIndexInSolvedataProfileTable.php
This migration will be executed when the plugin is updated to the latest version (i.e. when `magento setup:upgrade` is ran). In the worst case if the migration is not ran in a customer's environment when the plugin is updated, the behaviour will be the same as it is currently.
The plugin does not lookup emails by profile ID and therefore this index is solely used as a data constraint and dropping the index shouldn't have any negative performance implications.
**Before**
```
mysql> SHOW INDEX FROM solvedata.solvedata_profile;
+-------------------+------------+-------------------------------------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table             | Non_unique | Key_name …
```
=> Drop unique index on profile_id

.gitignore, README.md, docker/.env.example, docker/docker-compose.yml, docker/tools.sh, install.sh, vagrant/Vagrantfile, vagrant/provision.sh
This PR adds a Vagrantfile which runs Magento localdev store in docker-compose.
Setup should ideally be as easy as the following:
```
export MAGENTO_REPO_KEY='...'
export MAGENTO_REPO_SECRET='...'
vagrant up
```
I don't think this Vagrant localdev setup is ideal on the developer experience front, there is a lot of unnecessary complexity and gotchas that can catch you out. As a result of this PR I believe I think we now know enough of how this project is setup to attempt a pure docker-compose based localdev setup that mounts in the source directory. I also would like to simply & consolidate the `install.sh`, `tools.sh` & `provison.sh` scripts. In the meantime this PR should allow people to work on the plugin.
=> Add a Vagrantfile for reproducible localdev setup

Model/Event/Transport/Adapter/GraphQL/Mutation/CheckoutCartSaveAfter.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/ConvertCart.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/CreateOrUpdateOrder.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/CreateOrUpdatePayment.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/CreateOrUpdateReturn.php, Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, docker/tools.sh, tests/mutations/ConvertCartTest.php, tests/mutations/CreateOrUpdateOrderTest.php, tests/mutations/CreateOrUpdatePaymentTest.php, tests/mutations/CreateOrUpdateReturnTest.php, tests/mutations/RegisterCustomerTest.php
This PR fixes the inconsistent event timing between frontend SDK events & backend Magento events that customers see in a profile timeline in Solve.
It does this by:
- Setting the `created_at` date to the same instant as the Magento cart's `created_at`
- Setting `occurred_at` to the event's `created_at` time (the time that the event was persisted into the `solvedata_event` queue table) for the following GraphQL mutations
- `create_or_update_order`
- `create_or_update_cart`
- `create_or_update_payment`
- `create_or_update_return`
- Setting `occurred_at` to the order's `created_at` time for the `convert_cart` mutation
The PR also contains these unrelated fixes:
- Fixes current failing unit tests by adding in the missing dependency (regress caused by #51)
- Ignores another shellcheck warning …
=> Ensure order and cart events have timestamps consistent with Magento

Controller/Cart/Reclaim.php, Model/Event/RegisterHandler/Sales/OrderCancel.php, Model/Event/RegisterHandler/Sales/OrderSave.php, Model/Event/RegisterHandler/Sales/OrderShipmentSave.php, Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php
- Adds a little more context to the order state empty warnings & takes advantage of the recent Sentry changes so Sentry will parse the backtrace
- Fixes our (... or mine 😁) inconsistent use of `warn` vs `warning`. Appears like MonoLog 1.x allows you to use either overload while 2.x has removed `warn` in favour of `warning`. Therefore I decided it was best to consolidate on `warning`.
=> Add more context to order state empty warnings

Model/Event/RegisterHandler/Controller/StartCheckout.php, Model/Event/RegisterHandler/Converter.php, Model/Event/Transport/Adapter/GraphQL/Mutation/CheckoutCartSaveAfter/CreateOrUpdateCart.php, Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, Observer/Controller/StartCheckoutObserver.php, etc/config.xml, etc/events.xml, etc/solvedata_events.xml
This PR adds an observer that listens to `controller_action_predispatch_checkout_index_index` events, and queues up an event to create/update the session's cart with an extra flag called `quoteReachedCheckout` set.
This PR also fixed a long standing bug in the payload converter that prevented any scalars from being serialized in the top level of the payload.
=> Set the reached checkout flag on the customer's cart when checkout is started

Model/Event/RegisterHandler/Controller/StartCheckout.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesQuoteMergeAfter/CreateOrUpdateDestinationQuote.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesQuoteMergeAfter/CreateOrUpdateSourceQuote.php, Observer/ObserverAbstract.php
This PR adds defensive checks to prevent the extension from attempting mutations which will fail as key data in the event is missing.
While these errors were handled so the impact is minimal, we want to prevent noisy errors in our logs.
=> Don't attempt mutations if key data isn't present

Model/Event/RegisterHandler/Sales/OrderShipmentSave.php
We need to ensure we retrieve the order via the shipment object in the order shipment events. This regression was introduced by an accidental copy and paste error.
=> Fix regression in order shipment save's event handler

Model/Event.php, Model/Event/Transport/Adapter/GraphQL/Mutation/CreateOrUpdateOrder.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/CreateOrUpdatePayment.php, Model/Event/Transport/Adapter/GraphQL/Mutation/SalesOrderSaveAfter/CreateOrUpdateReturn.php, composer.json, etc/module.xml
This PR uses the order's "created at" timestamp as Solve's special occurred_at timestamps when importing orders into Solve.
It also fixes a bug where the payment details aren't present in imported order's payloads.
=> Fix occurred at for imported orders

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, Plugin/Quote/QuoteInterceptor.php
Fixes incorrect logger signature from being used inside error logging code paths that would result in uncaught exceptions from being thrown if these code paths were to be excised in production.
=> Pass exceptions into the logger's context record

composer.json, etc/module.xml
The `v2.0.2` release omitted the correct version in `composer.json` & `etc/module.xml`. This PR bumps the version up to `v2.0.3` to rectify this.
=> Bump extension version to v2.0.3

Model/Event/Transport/Adapter/GraphQL/PayloadConverter.php, Model/Logger/Handler/Sentry.php, Model/Logger/SentryHandler.php, composer.json, etc/module.xml
This PR fixes a regression introduced by #55 where the extension's use of Sentry was compatible with Sentry clients `>=3.0.0` but not the `3.0.0-beta1` version itself. The inclusion of the `3.0.0-beta1` Sentry version was done to support a particular environment whose transitive dependencies prevented composer from being able to resolve other versions.
The changes introduced in #55 worked with the version of Sentry resolved in our development & testing environments but failed when paired with Sentry version `^3.0.0-beta1`.
This PR fixes the Sentry version to `^3.0.0-beta1` in order to get predictable behaviour with a version known to work in client environments.
A future PR could investigate the feasibility of switching Sentry to use a version from `^2.0` as it's undesirable to be pined …
=> Pin sentry client to beta version

view/adminhtml/ui_component/solvedata_events_event_listing.xml
I'm unsure whether Magento 2.3.4 doesn't support the sticky parameter or whether the way its defined is actually invalid.
Either way the sticky parameter simply controls whether or not the top toolbar is visible when you scroll down. We wouldn't mind if it was configured either way.
=> Remove unnecessary element in view causing error in Magento 2.3.4

Model/ResourceModel/Event.php, Setup/Patch/Schema/AddCreatedAtAndStatusIndexesToSolvedataEvents.php, Setup/Patch/Schema/AddCreatedAtIndexToSolvedataEvents.php, Setup/Patch/Schema/DropSidUniqueIndexInSolvedataProfileTable.php
Before index:
```
mysql> explain select * from solvedata_event where created_at > '2020-01-01 00:00:00';
+----+-------------+-----------------+------------+------+---------------+------+---------+------+------+----------+-------------+
| id | select_type | table           | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra       |
+----+-------------+-----------------+------------+------+---------------+------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | solvedata_event | NULL       | ALL  | NULL          | NULL | NULL    | NULL |    1 |   100.00 | Using where |
+----+-------------+-----------------+------------+------+---------------+------+---------+------+------+----------+-------------+
1 row in set, 1 warning (0.00 sec)
``` …
=> SOLV 3319: Index events created at

Model/Event/RegisterHandler/EventAbstract.php, composer.json, etc/module.xml
The Magento extension uses a single instance of for each event handling strategy (i.e. subclasses of the `EventAbstract` abstract base class).
This is problematic because these strategies are also mutable and therefore there is the chance for data from one event to sweep into the processing of another completely different event.
While most fields would be overwritten with the new event's data, the payload field had its serialization result cached in a hidden field by the `EventAbstract` abstract base class. This resulted in subsequent events of the same type to reuse the payload from the first event and therefore effectively throwing away these subsequent events.
This bug fix, removes the complicated payload serialization caching in favour of serializing the payload just before it gets …
=> Fix incorrect event payload being cached when multiple events of the same type are processed

etc/adminhtml/system.xml, etc/config.xml
This PR reduces the default event retention period to 7 days inside the `solvedata_event` MySQL queueing table.
A reduction in the retention period means that Magento environments will have lower disk usage due to this extension, while 7 days is more than enough time to respond to incidents without losing data from the queue.
=> Reduce default event retention to 7 days

Console/Command/Import/Customer.php, Console/Command/Import/Order.php, Controller/Adminhtml/Customer/MassImport.php, Controller/Adminhtml/Event/ResendEvent.php, Controller/Adminhtml/Order/MassImport.php, LICENSE, Model/Event/RegisterHandler/EventAbstract.php, README.md, composer.json, etc/adminhtml/menu.xml, view/adminhtml/ui_component/customer_listing.xml, view/adminhtml/ui_component/sales_order_grid.xml
Simple PR to update the usages of "Solve Data" to "Solve" to be consistent with our branding.
=> Rebrand UI text to use the term Solve rather than Solve Data

etc/adminhtml/system.xml, view/adminhtml/layout/default.xml, view/adminhtml/web/css/solve.css
This PR is the first pass on making the extension's Admin configuration options accessible for customers seeking to setup their own Magento extensions.
Subsequent PRs will prune unnecessary configuration options and move most options into a collapsable group called "Advanced" which most users will be able to safely ignore when first setting up the extension.
=> Add comments to admin config page

vagrant/Makefile, vagrant/provision.sh
This PR enables us to use IDE with code completion by syncing the vendor directory out of Vagrant.
=> Add script to sync vendor dir out of Vagrant

Model/ResourceModel/Event.php
We've seen the the historical event purge cron job take serval hours/days to get through a backlog of events to purge.
This PR bumps the batch size it deletes at once by a factor of 10 to 10,000 every minute. This should be a good compromise between prompting deleting historical events while preventing the cronjob from locking the table (or locking the table for too long).
=> Increase the historical event purge batch size by a factor of 5
